name = "drawbang"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "drawbang"

[vars]
PUBLIC_BASE_URL = "https://drawbang.pages.dev"
