version = 0.1

[default.deploy.parameters]
stack_name = "drawbang-ingest"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = false
fail_on_empty_changeset = false
