// One-shot generator: rasterize src/layout/logo.ts's 42×16 wordmark SVG
// into a packed 1-bit bitmap committed at src/layout/logo-bitmap.ts. The
// share-image encoder (src/editor/share-gif.ts) needs pixel access to the
// wordmark at runtime; we lift the rasterization out of the GIF encode path
// so the runtime stays free of @resvg/resvg-js (a native binary unsuitable
// for Lambda's cold start). Re-run when LOGO_SVG changes and commit the
// regenerated file.
//
//   npm run og:logo-bitmap

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Resvg } from "@resvg/resvg-js";
import { LOGO_SVG } from "../src/layout/logo.js";

const LOGO_W = 42;
const LOGO_H = 16;

const tinted = LOGO_SVG.replace(`fill="currentColor"`, `fill="#ffffff"`);
const wrapped = `<svg xmlns="http://www.w3.org/2000/svg" width="${LOGO_W}" height="${LOGO_H}" viewBox="0 0 ${LOGO_W} ${LOGO_H}"><rect x="0" y="0" width="${LOGO_W}" height="${LOGO_H}" fill="#000000"/>${tinted}</svg>`;

const resvg = new Resvg(wrapped, {
  fitTo: { mode: "width", value: LOGO_W },
  shapeRendering: 2,
});
const png = resvg.render().asPng();

// Decode the PNG into a luma value per pixel. We use pngjs (already a
// dep) for the parse so we don't shell out.
const { PNG } = await import("pngjs");
const decoded = PNG.sync.read(Buffer.from(png));
if (decoded.width !== LOGO_W || decoded.height !== LOGO_H) {
  throw new Error(`unexpected raster size ${decoded.width}x${decoded.height}`);
}

const bits = new Uint8Array(LOGO_W * LOGO_H);
for (let i = 0, p = 0; i < bits.length; i++, p += 4) {
  // White-on-black source: brightness > 128 means "logo ink".
  const luma = (decoded.data[p] + decoded.data[p + 1] + decoded.data[p + 2]) / 3;
  bits[i] = luma > 128 ? 1 : 0;
}

const rows: string[] = [];
for (let y = 0; y < LOGO_H; y++) {
  const row = Array.from(bits.subarray(y * LOGO_W, (y + 1) * LOGO_W));
  rows.push("  " + row.join(",") + ",");
}

const out = `// generated by scripts/generate-logo-bitmap.ts — do not edit by hand.
// Rasterized from src/layout/logo.ts's LOGO_SVG. Regenerate with:
//   npm run og:logo-bitmap

export const LOGO_W = ${LOGO_W};
export const LOGO_H = ${LOGO_H};

// Row-major 0|1 bitmap, length LOGO_W * LOGO_H. 1 = ink, 0 = empty.
export const LOGO_BITMAP: Uint8Array = new Uint8Array([
${rows.join("\n")}
]);
`;

const outPath = resolve(import.meta.dirname, "..", "src", "layout", "logo-bitmap.ts");
writeFileSync(outPath, out);
console.log(`wrote ${outPath} (${LOGO_W}×${LOGO_H} bitmap, ${bits.reduce((s, b) => s + b, 0)} ink pixels)`);
